openapi: 3.1.0
info:
  title: EsePress OpenAPI Spec
  version: 0.0.1
servers:
  - url: http://localhost
    description: Localhost
paths:
  /:
    get:
      description: Show EsePress information
      responses:
        '200':
          description: Informations
          content:
            application/json:
              schema:
                type: object
                properties:
                  version:
                    type: string
